export const ProdectData = [
  {
    Name: "Men's Black Running",
    Gender: "Men",
    Type:"Running",
    Purchase:1,
    price: 79.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-005-600x600.jpg",
  },
  {
    Name: "Men's Classic Blue",
    Gender: "Men",
    Type:"Sneaker",
    Purchase:1,
    price: 69.0,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-019-600x600.jpg",
  },
  {
    Name: "Men's Classic Mint",
    Gender: "Men",
    Type:"Sneaker",
    Purchase:1,
    price: 79.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-020-600x600.jpg",
  },
  {
    Name: "Men's Earth-Tone Sneaker",
    Gender: "Men",
    Type:"Sneaker",
    Purchase:1,
    price: 74.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-017-600x600.jpg",
  },
  {
    Name: "Men's Green Running",
    Gender: "Men",
    Type:"Running",
    Purchase:1,
    price: 89.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-007-600x600.jpg",
  },
  {
    Name: "Men's Moonstone Sneaker",
    Gender: "Men",
    Type:"Sneaker",
    Purchase:1,
    price: 74.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-018-600x600.jpg",
  },
  {
    Name: "Men's Navy Running",
    Gender: "Men",
    Type:"Running",
    Purchase:1,
    price: 104.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-008-600x600.jpg",
  },
  {
    Name: "Men's Red Runnig",
    Gender: "Men",
    Type:"Running",
    Purchase:1,
    price: 69.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-006-600x600.jpg",
  },
  {
    Name: "Women's Blue Training",
    Gender: "Women",
    Type:"Training",
    Purchase:1,
    price: 60.0,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-003-600x600.jpg",
  },
  {
    Name: "Women's Candy City Run",
    Gender: "Women",
    Type:"Sneaker",
    Purchase:1,
    price: 40.0,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-014-600x600.jpg",
  },
  {
    Name: "Women's Choco City Run",
    Gender: "Women",
    Type:"Running",
    Purchase:1,
    price: 64.0,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-013-600x600.jpg",
  },
  {
    Name: "Women's Cream Suede",
    Gender: "Women",
    Type:"Sneaker",
    Purchase:1,
    price: 59.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-015-600x600.jpg",
  },
  {
    Name: "Women's Green Training",
    Gender: "Women",
    Type:"Training",
    Purchase:1,
    price: 49.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-001-600x600.jpg",
  },
  {
    Name: "Women's Mint Sneaker",
    Gender: "Women",
    Type:"Sneaker",
    Purchase:1,
    price: 89.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-010-600x600.jpg",
  },
  {
    Name: "Women's Orenge Sneaker",
    Gender: "Women",
    Type:"Sneaker",
    Purchase:1,
    price: 44.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-009-600x600.jpg",
  },
  {
    Name: "Women's Peach Training",
    Gender: "Women",
    Type:"Training",
    Purchase:1,
    price: 57.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-004-600x600.jpg",
  },
  {
    Name: "Women's Pink Suede",
    Gender: "Women",
    Type:"Sneaker",
    Purchase:1,
    price: 59.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-016-600x600.jpg",
  },
  {
    Name: "Women's Pink Training",
    Gender: "Women",
    Type:"Training",
    Purchase:1,
    price: 54.9,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-002-600x600.jpg",
  },
  {
    Name: "Women's Tan Sneaker",
    Gender: "Women",
    Type:"Sneaker",
    Purchase:1,
    price: 80.0,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-011-600x600.jpg",
  },
  {
    Name: "Women's Tosca City Run",
    Gender: "Women",
    Type:"Running",
    Purchase:1,
    price: 64.0,
    img: "https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-012-600x600.jpg",
  },
];
